service: express-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: af-south-1
  memorySize: 128

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000  